on:
  pull_request:
    branches: [master]
    paths:
      - 'app04/prod/nsg-app04-prod.bicep'
name: Check Production NSG - bicep
jobs:
  deploy-prod-nsg-bicep:
    runs-on: ubuntu-latest
    steps:
    # Checkout current repo
    - name: Checkout local repo
      uses: actions/checkout@main
    # Checkout remote repo (the path is important, the bicep template expects to find it there)
    - name: Checkout shared repo
      uses: actions/checkout@v2
      with:
        repository: erjosito/segmentation-iac
        path: './app04/prod/shared'
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy bicep template
    - name: Preflight check for infra bicep template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./app04/prod/nsg-app04-prod.bicep
        parameters: nsgName=app04-prod-nsg
        deploymentMode: Validate
