name: Remote AzFW deployment
on:
  repository_dispatch:

jobs:
  Remote-AzFW-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch triggering remote workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.SHARED_REPO_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/erjosito/segmentation-iac/actions/workflows/deploy_azfw_bicep_manual.yml/dispatches \
            -d '{"ref":"master"}'