on:
  push:
    branches: [master]
    paths:
      - 'app04/prod/nsg-app04-prod.bicep'
name: Deploy Production NSG - bicep
jobs:
  deploy-prod-nsg-bicep:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy bicep template
    - name: Run bicep deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./app04/prod/nsg-app04-prod.bicep
        parameters: nsgName='app04-prod-nsg'
